[package]
name = "monkey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "monkey"
path = "src/monkey-rs/lib.rs"

[[bin]]
name = "monkey"
path = "src/monkey-rs/main.rs"

[dependencies]
